# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get the sources
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install .NET Core SDK 8.0.x
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.x'

    - name: Install .NET Core SDK 9.0.x
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'

    - name: Install .NET SDK (global.json)
      uses: actions/setup-dotnet@v5
      with:
          global-json-file: global.json

    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{secrets.NUGET_USER}}

    - name: Run Cake script
      uses: cake-build/cake-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGET_TOKEN: ${{steps.login.outputs.NUGET_API_KEY}}
      with:
        cake-version: tool-manifest
        target: Release

    - uses: actions/upload-artifact@v4
      name: Upload Artifacts
      with:
        name: scedi-package
        path: dist/package/

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        body: |
          Install the package from NuGet or download the `nupkg` directly below.
        files: |
          ./dist/package/*.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
